// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VSpAttenSim.h for the primary calling header

#ifndef VERILATED_VSPATTENSIM_SPATTENSIM_H_
#define VERILATED_VSPATTENSIM_SPATTENSIM_H_  // guard

#include "verilated.h"
#include "verilated_threads.h"
class VSpAttenSim_SpAtten;


class VSpAttenSim__Syms;

class alignas(VL_CACHE_LINE_BYTES) VSpAttenSim_SpAttenSim final : public VerilatedModule {
  public:
    // CELLS
    VSpAttenSim_SpAtten* spatten_inst;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VlWide<8>/*255:0*/ __PVT__dram_insts_0__DOT__pending_resp_payload_data;
        VlWide<8>/*255:0*/ __PVT__dram_insts_1__DOT__pending_resp_payload_data;
        VlWide<8>/*255:0*/ __PVT__dram_insts_2__DOT__pending_resp_payload_data;
        VlWide<8>/*255:0*/ __PVT__dram_insts_3__DOT__pending_resp_payload_data;
        VlWide<8>/*255:0*/ __PVT__dram_insts_4__DOT__pending_resp_payload_data;
        VlWide<8>/*255:0*/ __PVT__dram_insts_5__DOT__pending_resp_payload_data;
        VlWide<8>/*255:0*/ __PVT__dram_insts_6__DOT__pending_resp_payload_data;
        VlWide<8>/*255:0*/ __PVT__dram_insts_7__DOT__pending_resp_payload_data;
        CData/*0:0*/ __PVT__dram_insts_2_dram_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_3_dram_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_0__DOT__pending_resp_payload_is_write;
        CData/*0:0*/ __PVT__dram_insts_1__DOT__pending_resp_payload_is_write;
        CData/*0:0*/ __PVT__dram_insts_2__DOT__pending_resp_payload_is_write;
        CData/*0:0*/ __PVT__dram_insts_3__DOT__pending_resp_payload_is_write;
        CData/*0:0*/ __PVT__dram_insts_4__DOT__pending_resp_payload_is_write;
        CData/*0:0*/ __PVT__dram_insts_5__DOT__pending_resp_payload_is_write;
        CData/*0:0*/ __PVT__dram_insts_6__DOT__pending_resp_payload_is_write;
        CData/*0:0*/ __PVT__dram_insts_7__DOT__pending_resp_payload_is_write;
        VlWide<8>/*255:0*/ __Vxrand_h4196b273__7;
        VlWide<8>/*255:0*/ __Vxrand_h4196b273__6;
        VlWide<8>/*255:0*/ __Vxrand_h4196b273__5;
        VlWide<8>/*255:0*/ __Vxrand_h4196b273__4;
        VlWide<8>/*255:0*/ __Vxrand_h4196b273__3;
        VlWide<8>/*255:0*/ __Vxrand_h4196b273__2;
        VlWide<8>/*255:0*/ __Vxrand_h4196b273__1;
        VlWide<8>/*255:0*/ __Vxrand_h4196b273__0;
        QData/*63:0*/ __PVT__dram_insts_0__DOT__obj;
        QData/*63:0*/ __PVT__dram_insts_0__DOT__pending_resp_payload_addr;
        QData/*63:0*/ __PVT__dram_insts_1__DOT__obj;
        QData/*63:0*/ __PVT__dram_insts_1__DOT__pending_resp_payload_addr;
        QData/*63:0*/ __PVT__dram_insts_2__DOT__obj;
        QData/*63:0*/ __PVT__dram_insts_2__DOT__pending_resp_payload_addr;
        QData/*63:0*/ __PVT__dram_insts_3__DOT__obj;
        QData/*63:0*/ __PVT__dram_insts_3__DOT__pending_resp_payload_addr;
        QData/*63:0*/ __PVT__dram_insts_4__DOT__obj;
        QData/*63:0*/ __PVT__dram_insts_4__DOT__pending_resp_payload_addr;
        QData/*63:0*/ __PVT__dram_insts_5__DOT__obj;
        QData/*63:0*/ __PVT__dram_insts_5__DOT__pending_resp_payload_addr;
        QData/*63:0*/ __PVT__dram_insts_6__DOT__obj;
        QData/*63:0*/ __PVT__dram_insts_6__DOT__pending_resp_payload_addr;
        QData/*63:0*/ __PVT__dram_insts_7__DOT__obj;
        QData/*63:0*/ __PVT__dram_insts_7__DOT__pending_resp_payload_addr;
        CData/*0:0*/ __PVT__dram_insts_4_dram_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_5_dram_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_4__DOT__pending_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_5__DOT__pending_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_0__DOT__pending_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_1__DOT__pending_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_6__DOT__pending_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_7__DOT__pending_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_2__DOT__pending_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_3__DOT__pending_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_0_dram_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_1_dram_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_6_dram_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_7_dram_resp_valid;
        CData/*0:0*/ __PVT__dram_insts_2__DOT__pending_req_valid;
        CData/*0:0*/ __PVT__dram_2_resp_ready;
        CData/*0:0*/ __PVT__streamFifo_65__DOT__logic_ptr_doPop;
        CData/*0:0*/ __PVT__streamFifo_65__DOT__logic_ptr_empty;
        CData/*0:0*/ __PVT__streamFifo_65__DOT__logic_pop_addressGen_ready;
        CData/*0:0*/ __PVT__streamFifo_65__DOT__logic_pop_addressGen_rValid;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_2_ar_fork2_logic_linkEnable_0;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_2_ar_fork2_logic_linkEnable_1;
    };
    struct {
        CData/*0:0*/ __PVT__streamFifo_65__DOT__logic_ptr_full;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_2_ar_fork2_outputs_0_fire;
        CData/*0:0*/ __PVT__streamFifo_65__DOT___zz_1;
        CData/*0:0*/ __PVT__dram_2_req_valid;
        CData/*0:0*/ __PVT__streamFifo_64__DOT__logic_ptr_wentUp;
        CData/*6:0*/ __PVT__streamFifo_65__DOT__logic_ptr_push;
        CData/*6:0*/ __PVT__streamFifo_65__DOT__logic_ptr_pop;
        CData/*0:0*/ __PVT__streamFifo_65__DOT__logic_ptr_wentUp;
        CData/*5:0*/ __PVT__streamFifo_65__DOT__logic_pop_addressGen_rData;
        CData/*6:0*/ __PVT__streamFifo_65__DOT__logic_pop_sync_popReg;
        CData/*5:0*/ __Vdlyvdim0__streamFifo_65__DOT__logic_ram__v0;
        CData/*3:0*/ __Vdlyvval__streamFifo_65__DOT__logic_ram__v0;
        CData/*0:0*/ __Vdlyvset__streamFifo_65__DOT__logic_ram__v0;
        CData/*6:0*/ __Vdly__streamFifo_65__DOT__logic_ptr_push;
        CData/*6:0*/ __Vdly__streamFifo_65__DOT__logic_ptr_pop;
        VlUnpacked<CData/*3:0*/, 64> __PVT__streamFifo_65__DOT__logic_ram;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_0_ar_fork2_outputs_0_fire;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_5_ar_fork2_outputs_0_fire;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_6_ar_fork2_outputs_0_fire;
        CData/*0:0*/ __PVT__streamFifo_63__DOT___zz_1;
        CData/*6:0*/ __PVT__streamFifo_63__DOT__logic_ptr_push;
        CData/*6:0*/ __PVT__streamFifo_63__DOT__logic_ptr_pop;
        CData/*0:0*/ __PVT__streamFifo_63__DOT__logic_ptr_wentUp;
        CData/*5:0*/ __PVT__streamFifo_63__DOT__logic_pop_addressGen_rData;
        CData/*6:0*/ __PVT__streamFifo_63__DOT__logic_pop_sync_popReg;
        CData/*0:0*/ __PVT__streamFifo_68__DOT__logic_ptr_wentUp;
        CData/*0:0*/ __PVT__streamFifo_69__DOT__logic_ptr_wentUp;
        CData/*5:0*/ __Vdlyvdim0__streamFifo_63__DOT__logic_ram__v0;
        CData/*3:0*/ __Vdlyvval__streamFifo_63__DOT__logic_ram__v0;
        CData/*0:0*/ __Vdlyvset__streamFifo_63__DOT__logic_ram__v0;
        CData/*6:0*/ __Vdly__streamFifo_63__DOT__logic_ptr_push;
        CData/*6:0*/ __Vdly__streamFifo_63__DOT__logic_ptr_pop;
        VlUnpacked<CData/*3:0*/, 64> __PVT__streamFifo_63__DOT__logic_ram;
        CData/*0:0*/ __PVT__streamFifo_63__DOT__logic_ptr_full;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_7_ar_fork2_logic_linkEnable_0;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_7_ar_fork2_logic_linkEnable_1;
        CData/*0:0*/ __PVT__streamFifo_67__DOT__logic_ptr_full;
        CData/*0:0*/ __PVT__streamFifo_70__DOT__logic_ptr_full;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_7_ar_fork2_outputs_0_fire;
        CData/*0:0*/ __PVT__streamFifo_67__DOT___zz_1;
        CData/*0:0*/ __PVT__streamFifo_70__DOT___zz_1;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_3_ar_fork2_outputs_0_fire;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_4_ar_fork2_outputs_0_fire;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_1_ar_fork2_outputs_0_fire;
        CData/*0:0*/ __PVT__streamFifo_64__DOT__logic_ptr_doPop;
        CData/*0:0*/ __PVT__dram_0_req_valid;
        CData/*0:0*/ __PVT__dram_1_req_valid;
        CData/*0:0*/ __PVT__dram_1_resp_ready;
        CData/*0:0*/ __PVT__dram_3_req_valid;
        CData/*0:0*/ __PVT__dram_4_req_valid;
        CData/*0:0*/ __PVT__dram_5_req_valid;
        CData/*0:0*/ __PVT__dram_6_req_valid;
        CData/*0:0*/ __PVT__dram_7_req_valid;
        CData/*0:0*/ __PVT__streamFifo_66__DOT__logic_ptr_wentUp;
        CData/*6:0*/ __PVT__streamFifo_67__DOT__logic_ptr_push;
        CData/*6:0*/ __PVT__streamFifo_67__DOT__logic_ptr_pop;
        CData/*0:0*/ __PVT__streamFifo_67__DOT__logic_ptr_wentUp;
        CData/*5:0*/ __PVT__streamFifo_67__DOT__logic_pop_addressGen_rData;
        CData/*6:0*/ __PVT__streamFifo_67__DOT__logic_pop_sync_popReg;
        CData/*6:0*/ __PVT__streamFifo_70__DOT__logic_ptr_push;
        CData/*6:0*/ __PVT__streamFifo_70__DOT__logic_ptr_pop;
        CData/*0:0*/ __PVT__streamFifo_70__DOT__logic_ptr_wentUp;
        CData/*5:0*/ __PVT__streamFifo_70__DOT__logic_pop_addressGen_rData;
        CData/*6:0*/ __PVT__streamFifo_70__DOT__logic_pop_sync_popReg;
    };
    struct {
        CData/*5:0*/ __Vdlyvdim0__streamFifo_67__DOT__logic_ram__v0;
        CData/*3:0*/ __Vdlyvval__streamFifo_67__DOT__logic_ram__v0;
        CData/*0:0*/ __Vdlyvset__streamFifo_67__DOT__logic_ram__v0;
        CData/*6:0*/ __Vdly__streamFifo_67__DOT__logic_ptr_push;
        CData/*6:0*/ __Vdly__streamFifo_67__DOT__logic_ptr_pop;
        CData/*5:0*/ __Vdlyvdim0__streamFifo_70__DOT__logic_ram__v0;
        CData/*3:0*/ __Vdlyvval__streamFifo_70__DOT__logic_ram__v0;
        CData/*0:0*/ __Vdlyvset__streamFifo_70__DOT__logic_ram__v0;
        CData/*6:0*/ __Vdly__streamFifo_70__DOT__logic_ptr_push;
        CData/*6:0*/ __Vdly__streamFifo_70__DOT__logic_ptr_pop;
        VlUnpacked<CData/*3:0*/, 64> __PVT__streamFifo_67__DOT__logic_ram;
        VlUnpacked<CData/*3:0*/, 64> __PVT__streamFifo_70__DOT__logic_ram;
        CData/*0:0*/ __PVT__streamFifo_66__DOT__logic_ptr_doPop;
        CData/*6:0*/ __PVT__streamFifo_64__DOT__logic_ptr_push;
        CData/*6:0*/ __PVT__streamFifo_64__DOT__logic_ptr_pop;
        CData/*5:0*/ __PVT__streamFifo_64__DOT__logic_pop_addressGen_rData;
        CData/*6:0*/ __PVT__streamFifo_64__DOT__logic_pop_sync_popReg;
        CData/*6:0*/ __PVT__streamFifo_66__DOT__logic_ptr_push;
        CData/*6:0*/ __PVT__streamFifo_66__DOT__logic_ptr_pop;
        CData/*5:0*/ __PVT__streamFifo_66__DOT__logic_pop_addressGen_rData;
        CData/*6:0*/ __PVT__streamFifo_66__DOT__logic_pop_sync_popReg;
        CData/*6:0*/ __PVT__streamFifo_68__DOT__logic_ptr_push;
        CData/*6:0*/ __PVT__streamFifo_68__DOT__logic_ptr_pop;
        CData/*5:0*/ __PVT__streamFifo_68__DOT__logic_pop_addressGen_rData;
        CData/*6:0*/ __PVT__streamFifo_68__DOT__logic_pop_sync_popReg;
        CData/*6:0*/ __PVT__streamFifo_69__DOT__logic_ptr_push;
        CData/*6:0*/ __PVT__streamFifo_69__DOT__logic_ptr_pop;
        CData/*5:0*/ __PVT__streamFifo_69__DOT__logic_pop_addressGen_rData;
        CData/*6:0*/ __PVT__streamFifo_69__DOT__logic_pop_sync_popReg;
        CData/*5:0*/ __Vdlyvdim0__streamFifo_64__DOT__logic_ram__v0;
        CData/*3:0*/ __Vdlyvval__streamFifo_64__DOT__logic_ram__v0;
        CData/*0:0*/ __Vdlyvset__streamFifo_64__DOT__logic_ram__v0;
        CData/*6:0*/ __Vdly__streamFifo_64__DOT__logic_ptr_push;
        CData/*6:0*/ __Vdly__streamFifo_64__DOT__logic_ptr_pop;
        CData/*5:0*/ __Vdlyvdim0__streamFifo_66__DOT__logic_ram__v0;
        CData/*3:0*/ __Vdlyvval__streamFifo_66__DOT__logic_ram__v0;
        CData/*0:0*/ __Vdlyvset__streamFifo_66__DOT__logic_ram__v0;
        CData/*6:0*/ __Vdly__streamFifo_66__DOT__logic_ptr_push;
        CData/*6:0*/ __Vdly__streamFifo_66__DOT__logic_ptr_pop;
        CData/*5:0*/ __Vdlyvdim0__streamFifo_68__DOT__logic_ram__v0;
        CData/*3:0*/ __Vdlyvval__streamFifo_68__DOT__logic_ram__v0;
        CData/*0:0*/ __Vdlyvset__streamFifo_68__DOT__logic_ram__v0;
        CData/*6:0*/ __Vdly__streamFifo_68__DOT__logic_ptr_push;
        CData/*6:0*/ __Vdly__streamFifo_68__DOT__logic_ptr_pop;
        CData/*5:0*/ __Vdlyvdim0__streamFifo_69__DOT__logic_ram__v0;
        CData/*3:0*/ __Vdlyvval__streamFifo_69__DOT__logic_ram__v0;
        CData/*0:0*/ __Vdlyvset__streamFifo_69__DOT__logic_ram__v0;
        CData/*6:0*/ __Vdly__streamFifo_69__DOT__logic_ptr_push;
        CData/*6:0*/ __Vdly__streamFifo_69__DOT__logic_ptr_pop;
        VlUnpacked<CData/*3:0*/, 64> __PVT__streamFifo_64__DOT__logic_ram;
        VlUnpacked<CData/*3:0*/, 64> __PVT__streamFifo_66__DOT__logic_ram;
        VlUnpacked<CData/*3:0*/, 64> __PVT__streamFifo_68__DOT__logic_ram;
        VlUnpacked<CData/*3:0*/, 64> __PVT__streamFifo_69__DOT__logic_ram;
        CData/*0:0*/ __PVT__dram_insts_0__DOT__pending_req_valid;
        CData/*0:0*/ __PVT__dram_insts_1__DOT__pending_req_valid;
        CData/*0:0*/ __PVT__dram_insts_3__DOT__pending_req_valid;
        CData/*0:0*/ __PVT__dram_insts_4__DOT__pending_req_valid;
        CData/*0:0*/ __PVT__dram_insts_5__DOT__pending_req_valid;
        CData/*0:0*/ __PVT__dram_insts_6__DOT__pending_req_valid;
        CData/*0:0*/ __PVT__dram_insts_0__DOT__pending_req_payload_is_write;
        CData/*0:0*/ __PVT__dram_insts_1__DOT__pending_req_payload_is_write;
        CData/*0:0*/ __PVT__dram_insts_2__DOT__pending_req_payload_is_write;
        CData/*0:0*/ __PVT__dram_insts_3__DOT__pending_req_payload_is_write;
        CData/*0:0*/ __PVT__dram_insts_4__DOT__pending_req_payload_is_write;
    };
    struct {
        CData/*0:0*/ __PVT__dram_insts_5__DOT__pending_req_payload_is_write;
        CData/*0:0*/ __PVT__dram_insts_6__DOT__pending_req_payload_is_write;
        CData/*0:0*/ __PVT__dram_insts_7__DOT__pending_req_payload_is_write;
        CData/*0:0*/ __Vdly__dram_insts_0__DOT__pending_req_valid;
        CData/*0:0*/ __Vdly__dram_insts_1__DOT__pending_req_valid;
        CData/*0:0*/ __Vdly__dram_insts_2__DOT__pending_req_valid;
        CData/*0:0*/ __Vdly__dram_insts_3__DOT__pending_req_valid;
        CData/*0:0*/ __Vdly__dram_insts_4__DOT__pending_req_valid;
        CData/*0:0*/ __Vdly__dram_insts_5__DOT__pending_req_valid;
        CData/*0:0*/ __Vdly__dram_insts_6__DOT__pending_req_valid;
        CData/*0:0*/ __Vdly__dram_insts_7__DOT__pending_req_valid;
        VlWide<8>/*255:0*/ __PVT__dram_insts_0__DOT__pending_req_payload_data;
        VlWide<8>/*255:0*/ __PVT__dram_insts_1__DOT__pending_req_payload_data;
        VlWide<8>/*255:0*/ __PVT__dram_insts_2__DOT__pending_req_payload_data;
        VlWide<8>/*255:0*/ __PVT__dram_insts_3__DOT__pending_req_payload_data;
        VlWide<8>/*255:0*/ __PVT__dram_insts_4__DOT__pending_req_payload_data;
        VlWide<8>/*255:0*/ __PVT__dram_insts_5__DOT__pending_req_payload_data;
        VlWide<8>/*255:0*/ __PVT__dram_insts_6__DOT__pending_req_payload_data;
        VlWide<8>/*255:0*/ __PVT__dram_insts_7__DOT__pending_req_payload_data;
        QData/*63:0*/ __PVT__dram_insts_0__DOT__pending_req_payload_addr;
        QData/*63:0*/ __PVT__dram_insts_1__DOT__pending_req_payload_addr;
        QData/*63:0*/ __PVT__dram_insts_2__DOT__pending_req_payload_addr;
        QData/*63:0*/ __PVT__dram_insts_3__DOT__pending_req_payload_addr;
        QData/*63:0*/ __PVT__dram_insts_4__DOT__pending_req_payload_addr;
        QData/*63:0*/ __PVT__dram_insts_5__DOT__pending_req_payload_addr;
        QData/*63:0*/ __PVT__dram_insts_6__DOT__pending_req_payload_addr;
        QData/*63:0*/ __PVT__dram_insts_7__DOT__pending_req_payload_addr;
        CData/*0:0*/ __PVT__dram_insts_7__DOT__pending_req_valid;
        CData/*0:0*/ __PVT__dram_4_resp_ready;
        CData/*0:0*/ __PVT__dram_7_resp_ready;
        CData/*0:0*/ __PVT__streamFifo_67__DOT__logic_ptr_doPop;
        CData/*0:0*/ __PVT__streamFifo_67__DOT__logic_ptr_empty;
        CData/*0:0*/ __PVT__streamFifo_67__DOT__logic_pop_addressGen_ready;
        CData/*0:0*/ __PVT__streamFifo_70__DOT__logic_ptr_doPop;
        CData/*0:0*/ __PVT__streamFifo_70__DOT__logic_ptr_empty;
        CData/*0:0*/ __PVT__streamFifo_70__DOT__logic_pop_addressGen_ready;
        CData/*0:0*/ __PVT__streamFifo_67__DOT__logic_pop_addressGen_rValid;
        CData/*0:0*/ __PVT__streamFifo_70__DOT__logic_pop_addressGen_rValid;
        CData/*0:0*/ __PVT___zz_io_bus_7_r_valid;
        CData/*3:0*/ __PVT__streamFifo_70__DOT___zz_logic_ram_port1;
        CData/*0:0*/ __PVT___zz_io_bus_0_r_valid;
        CData/*3:0*/ __PVT__streamFifo_63__DOT___zz_logic_ram_port1;
        CData/*0:0*/ __PVT__streamFifo_63__DOT__logic_pop_addressGen_rValid;
        CData/*0:0*/ __PVT__streamFifo_63__DOT__logic_ptr_doPop;
        CData/*0:0*/ __PVT__streamFifo_63__DOT__logic_ptr_empty;
        CData/*0:0*/ __PVT__streamFifo_63__DOT__logic_pop_addressGen_ready;
        CData/*0:0*/ __PVT__dram_0_resp_ready;
        CData/*0:0*/ __PVT__streamFifo_68__DOT__logic_ptr_doPop;
        CData/*0:0*/ __PVT__streamFifo_69__DOT__logic_ptr_doPop;
        CData/*0:0*/ __PVT__streamFifo_66__DOT__logic_ptr_empty;
        CData/*0:0*/ __PVT__streamFifo_66__DOT__logic_pop_addressGen_ready;
        CData/*0:0*/ __PVT__streamFifo_68__DOT__logic_ptr_empty;
        CData/*0:0*/ __PVT__streamFifo_68__DOT__logic_pop_addressGen_ready;
        CData/*0:0*/ __PVT__streamFifo_69__DOT__logic_ptr_empty;
        CData/*0:0*/ __PVT__streamFifo_69__DOT__logic_pop_addressGen_ready;
        CData/*0:0*/ __PVT__dram_3_resp_ready;
        CData/*0:0*/ __PVT__dram_5_resp_ready;
        CData/*0:0*/ __PVT__dram_6_resp_ready;
        CData/*0:0*/ __PVT__streamFifo_66__DOT__logic_pop_addressGen_rValid;
        CData/*0:0*/ __PVT__streamFifo_68__DOT__logic_pop_addressGen_rValid;
        CData/*0:0*/ __PVT__streamFifo_69__DOT__logic_pop_addressGen_rValid;
        CData/*0:0*/ __PVT___zz_io_bus_6_r_valid;
        CData/*3:0*/ __PVT__streamFifo_69__DOT___zz_logic_ram_port1;
        CData/*0:0*/ __PVT___zz_io_bus_3_r_valid;
    };
    struct {
        CData/*0:0*/ __PVT___zz_io_bus_5_r_valid;
        CData/*3:0*/ __PVT__streamFifo_66__DOT___zz_logic_ram_port1;
        CData/*3:0*/ __PVT__streamFifo_68__DOT___zz_logic_ram_port1;
        CData/*0:0*/ __PVT___zz_io_bus_2_r_valid;
        CData/*3:0*/ __PVT__streamFifo_65__DOT___zz_logic_ram_port1;
        CData/*0:0*/ __PVT___zz_io_bus_4_r_valid;
        CData/*3:0*/ __PVT__streamFifo_67__DOT___zz_logic_ram_port1;
        CData/*0:0*/ __PVT___zz_io_bus_1_r_valid;
        CData/*3:0*/ __PVT__streamFifo_64__DOT___zz_logic_ram_port1;
        CData/*0:0*/ __PVT__streamFifo_64__DOT__logic_pop_addressGen_rValid;
        CData/*0:0*/ __PVT__streamFifo_64__DOT___zz_1;
        CData/*0:0*/ __PVT__streamFifo_64__DOT__logic_ptr_empty;
        CData/*0:0*/ __PVT__streamFifo_64__DOT__logic_pop_addressGen_ready;
        CData/*0:0*/ __PVT__streamFifo_66__DOT___zz_1;
        CData/*0:0*/ __PVT__streamFifo_68__DOT___zz_1;
        CData/*0:0*/ __PVT__streamFifo_69__DOT___zz_1;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_0_ar_fork2_logic_linkEnable_0;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_0_ar_fork2_logic_linkEnable_1;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_1_ar_fork2_logic_linkEnable_0;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_1_ar_fork2_logic_linkEnable_1;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_3_ar_fork2_logic_linkEnable_0;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_3_ar_fork2_logic_linkEnable_1;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_4_ar_fork2_logic_linkEnable_0;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_4_ar_fork2_logic_linkEnable_1;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_5_ar_fork2_logic_linkEnable_0;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_5_ar_fork2_logic_linkEnable_1;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_6_ar_fork2_logic_linkEnable_0;
        CData/*0:0*/ __PVT__toplevel_spatten_inst_io_bus_6_ar_fork2_logic_linkEnable_1;
        CData/*0:0*/ __PVT__streamFifo_64__DOT__logic_ptr_full;
        CData/*0:0*/ __PVT__streamFifo_66__DOT__logic_ptr_full;
        CData/*0:0*/ __PVT__streamFifo_68__DOT__logic_ptr_full;
        CData/*0:0*/ __PVT__streamFifo_69__DOT__logic_ptr_full;
        CData/*0:0*/ __PVT__spatten_inst_io_bus_0_ar_ready;
        CData/*0:0*/ __PVT__spatten_inst_io_bus_1_ar_ready;
        CData/*0:0*/ __PVT__spatten_inst_io_bus_3_ar_ready;
        CData/*0:0*/ __PVT__spatten_inst_io_bus_4_ar_ready;
        CData/*0:0*/ __PVT__spatten_inst_io_bus_5_ar_ready;
        CData/*0:0*/ __PVT__spatten_inst_io_bus_6_ar_ready;
        CData/*0:0*/ __PVT__spatten_inst_io_bus_2_ar_ready;
        CData/*0:0*/ __PVT__spatten_inst_io_bus_7_ar_ready;
        VL_IN8(clk,0,0);
        VL_IN8(io_req_valid,0,0);
        VL_OUT8(io_req_ready,0,0);
        VL_IN8(io_req_payload_last,0,0);
        VL_IN8(io_req_payload_fragment_metadata_profile_key_bit_count,3,0);
        VL_IN8(io_req_payload_fragment_metadata_profile_key_fused_mat,1,0);
        VL_IN8(io_req_payload_fragment_metadata_profile_val_bit_count,3,0);
        VL_IN8(io_req_payload_fragment_metadata_profile_val_fused_mat,1,0);
        VL_IN8(io_req_payload_fragment_metadata_key_fetch_num,7,0);
        VL_IN8(io_req_payload_fragment_metadata_val_fetch_num,7,0);
        VL_IN8(io_req_payload_fragment_metadata_topk_enable,0,0);
        VL_IN8(io_req_payload_fragment_metadata_topk_num,7,0);
        VL_IN8(io_req_payload_fragment_metadata_size_d,6,0);
        VL_IN8(io_req_payload_fragment_metadata_allow_requantize,0,0);
        VL_OUT8(io_resp_valid,0,0);
        VL_IN8(io_resp_ready,0,0);
        VL_OUT8(io_resp_payload_metadata_profile_key_bit_count,3,0);
        VL_OUT8(io_resp_payload_metadata_profile_key_fused_mat,1,0);
        VL_OUT8(io_resp_payload_metadata_profile_val_bit_count,3,0);
        VL_OUT8(io_resp_payload_metadata_profile_val_fused_mat,1,0);
        VL_OUT8(io_resp_payload_metadata_key_fetch_num,7,0);
        VL_OUT8(io_resp_payload_metadata_val_fetch_num,7,0);
        VL_OUT8(io_resp_payload_metadata_topk_enable,0,0);
        VL_OUT8(io_resp_payload_metadata_topk_num,7,0);
    };
    struct {
        VL_OUT8(io_resp_payload_metadata_size_d,6,0);
        VL_OUT8(io_resp_payload_metadata_allow_requantize,0,0);
        VL_IN8(reset,0,0);
        VL_IN16(io_req_payload_fragment_query_0,11,0);
        VL_IN16(io_req_payload_fragment_query_1,11,0);
        VL_IN16(io_req_payload_fragment_query_2,11,0);
        VL_IN16(io_req_payload_fragment_query_3,11,0);
        VL_IN16(io_req_payload_fragment_query_4,11,0);
        VL_IN16(io_req_payload_fragment_query_5,11,0);
        VL_IN16(io_req_payload_fragment_query_6,11,0);
        VL_IN16(io_req_payload_fragment_query_7,11,0);
        VL_IN16(io_req_payload_fragment_query_8,11,0);
        VL_IN16(io_req_payload_fragment_query_9,11,0);
        VL_IN16(io_req_payload_fragment_query_10,11,0);
        VL_IN16(io_req_payload_fragment_query_11,11,0);
        VL_IN16(io_req_payload_fragment_query_12,11,0);
        VL_IN16(io_req_payload_fragment_query_13,11,0);
        VL_IN16(io_req_payload_fragment_query_14,11,0);
        VL_IN16(io_req_payload_fragment_query_15,11,0);
        VL_IN16(io_req_payload_fragment_query_16,11,0);
        VL_IN16(io_req_payload_fragment_query_17,11,0);
        VL_IN16(io_req_payload_fragment_query_18,11,0);
        VL_IN16(io_req_payload_fragment_query_19,11,0);
        VL_IN16(io_req_payload_fragment_query_20,11,0);
        VL_IN16(io_req_payload_fragment_query_21,11,0);
        VL_IN16(io_req_payload_fragment_query_22,11,0);
        VL_IN16(io_req_payload_fragment_query_23,11,0);
        VL_IN16(io_req_payload_fragment_query_24,11,0);
        VL_IN16(io_req_payload_fragment_query_25,11,0);
        VL_IN16(io_req_payload_fragment_query_26,11,0);
        VL_IN16(io_req_payload_fragment_query_27,11,0);
        VL_IN16(io_req_payload_fragment_query_28,11,0);
        VL_IN16(io_req_payload_fragment_query_29,11,0);
        VL_IN16(io_req_payload_fragment_query_30,11,0);
        VL_IN16(io_req_payload_fragment_query_31,11,0);
        VL_IN16(io_req_payload_fragment_query_32,11,0);
        VL_IN16(io_req_payload_fragment_query_33,11,0);
        VL_IN16(io_req_payload_fragment_query_34,11,0);
        VL_IN16(io_req_payload_fragment_query_35,11,0);
        VL_IN16(io_req_payload_fragment_query_36,11,0);
        VL_IN16(io_req_payload_fragment_query_37,11,0);
        VL_IN16(io_req_payload_fragment_query_38,11,0);
        VL_IN16(io_req_payload_fragment_query_39,11,0);
        VL_IN16(io_req_payload_fragment_query_40,11,0);
        VL_IN16(io_req_payload_fragment_query_41,11,0);
        VL_IN16(io_req_payload_fragment_query_42,11,0);
        VL_IN16(io_req_payload_fragment_query_43,11,0);
        VL_IN16(io_req_payload_fragment_query_44,11,0);
        VL_IN16(io_req_payload_fragment_query_45,11,0);
        VL_IN16(io_req_payload_fragment_query_46,11,0);
        VL_IN16(io_req_payload_fragment_query_47,11,0);
        VL_IN16(io_req_payload_fragment_query_48,11,0);
        VL_IN16(io_req_payload_fragment_query_49,11,0);
        VL_IN16(io_req_payload_fragment_query_50,11,0);
        VL_IN16(io_req_payload_fragment_query_51,11,0);
        VL_IN16(io_req_payload_fragment_query_52,11,0);
        VL_IN16(io_req_payload_fragment_query_53,11,0);
        VL_IN16(io_req_payload_fragment_query_54,11,0);
        VL_IN16(io_req_payload_fragment_query_55,11,0);
        VL_IN16(io_req_payload_fragment_query_56,11,0);
        VL_IN16(io_req_payload_fragment_query_57,11,0);
        VL_IN16(io_req_payload_fragment_query_58,11,0);
        VL_IN16(io_req_payload_fragment_query_59,11,0);
        VL_IN16(io_req_payload_fragment_query_60,11,0);
    };
    struct {
        VL_IN16(io_req_payload_fragment_query_61,11,0);
        VL_IN16(io_req_payload_fragment_query_62,11,0);
        VL_IN16(io_req_payload_fragment_query_63,11,0);
        VL_IN16(io_req_payload_fragment_metadata_thres_requantize,11,0);
        VL_OUT16(io_resp_payload_results_0,11,0);
        VL_OUT16(io_resp_payload_results_1,11,0);
        VL_OUT16(io_resp_payload_results_2,11,0);
        VL_OUT16(io_resp_payload_results_3,11,0);
        VL_OUT16(io_resp_payload_results_4,11,0);
        VL_OUT16(io_resp_payload_results_5,11,0);
        VL_OUT16(io_resp_payload_results_6,11,0);
        VL_OUT16(io_resp_payload_results_7,11,0);
        VL_OUT16(io_resp_payload_results_8,11,0);
        VL_OUT16(io_resp_payload_results_9,11,0);
        VL_OUT16(io_resp_payload_results_10,11,0);
        VL_OUT16(io_resp_payload_results_11,11,0);
        VL_OUT16(io_resp_payload_results_12,11,0);
        VL_OUT16(io_resp_payload_results_13,11,0);
        VL_OUT16(io_resp_payload_results_14,11,0);
        VL_OUT16(io_resp_payload_results_15,11,0);
        VL_OUT16(io_resp_payload_results_16,11,0);
        VL_OUT16(io_resp_payload_results_17,11,0);
        VL_OUT16(io_resp_payload_results_18,11,0);
        VL_OUT16(io_resp_payload_results_19,11,0);
        VL_OUT16(io_resp_payload_results_20,11,0);
        VL_OUT16(io_resp_payload_results_21,11,0);
        VL_OUT16(io_resp_payload_results_22,11,0);
        VL_OUT16(io_resp_payload_results_23,11,0);
        VL_OUT16(io_resp_payload_results_24,11,0);
        VL_OUT16(io_resp_payload_results_25,11,0);
        VL_OUT16(io_resp_payload_results_26,11,0);
        VL_OUT16(io_resp_payload_results_27,11,0);
        VL_OUT16(io_resp_payload_results_28,11,0);
        VL_OUT16(io_resp_payload_results_29,11,0);
        VL_OUT16(io_resp_payload_results_30,11,0);
        VL_OUT16(io_resp_payload_results_31,11,0);
        VL_OUT16(io_resp_payload_results_32,11,0);
        VL_OUT16(io_resp_payload_results_33,11,0);
        VL_OUT16(io_resp_payload_results_34,11,0);
        VL_OUT16(io_resp_payload_results_35,11,0);
        VL_OUT16(io_resp_payload_results_36,11,0);
        VL_OUT16(io_resp_payload_results_37,11,0);
        VL_OUT16(io_resp_payload_results_38,11,0);
        VL_OUT16(io_resp_payload_results_39,11,0);
        VL_OUT16(io_resp_payload_results_40,11,0);
        VL_OUT16(io_resp_payload_results_41,11,0);
        VL_OUT16(io_resp_payload_results_42,11,0);
        VL_OUT16(io_resp_payload_results_43,11,0);
        VL_OUT16(io_resp_payload_results_44,11,0);
        VL_OUT16(io_resp_payload_results_45,11,0);
        VL_OUT16(io_resp_payload_results_46,11,0);
        VL_OUT16(io_resp_payload_results_47,11,0);
        VL_OUT16(io_resp_payload_results_48,11,0);
        VL_OUT16(io_resp_payload_results_49,11,0);
        VL_OUT16(io_resp_payload_results_50,11,0);
        VL_OUT16(io_resp_payload_results_51,11,0);
        VL_OUT16(io_resp_payload_results_52,11,0);
        VL_OUT16(io_resp_payload_results_53,11,0);
        VL_OUT16(io_resp_payload_results_54,11,0);
        VL_OUT16(io_resp_payload_results_55,11,0);
        VL_OUT16(io_resp_payload_results_56,11,0);
        VL_OUT16(io_resp_payload_results_57,11,0);
        VL_OUT16(io_resp_payload_results_58,11,0);
        VL_OUT16(io_resp_payload_results_59,11,0);
    };
    struct {
        VL_OUT16(io_resp_payload_results_60,11,0);
        VL_OUT16(io_resp_payload_results_61,11,0);
        VL_OUT16(io_resp_payload_results_62,11,0);
        VL_OUT16(io_resp_payload_results_63,11,0);
        VL_OUT16(io_resp_payload_metadata_thres_requantize,11,0);
        VL_IN(io_req_payload_fragment_metadata_key_base_addr,31,0);
        VL_IN(io_req_payload_fragment_metadata_key_requant_base_addr,31,0);
        VL_IN(io_req_payload_fragment_metadata_val_base_addr,31,0);
        VL_IN(io_req_payload_fragment_metadata_universal_id,31,0);
        VL_IN(io_req_payload_fragment_metadata_topk_latency,31,0);
        VL_OUT(io_resp_payload_metadata_key_base_addr,31,0);
        VL_OUT(io_resp_payload_metadata_key_requant_base_addr,31,0);
        VL_OUT(io_resp_payload_metadata_val_base_addr,31,0);
        VL_OUT(io_resp_payload_metadata_universal_id,31,0);
        VL_OUT(io_resp_payload_metadata_topk_latency,31,0);
    };

    // INTERNAL VARIABLES
    VSpAttenSim__Syms* const vlSymsp;

    // CONSTRUCTORS
    VSpAttenSim_SpAttenSim(VSpAttenSim__Syms* symsp, const char* v__name);
    ~VSpAttenSim_SpAttenSim();
    VL_UNCOPYABLE(VSpAttenSim_SpAttenSim);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
